AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: AWS SAM template for deploying a serverless API with a global DynamoDB table

Parameters:

Globals:
  Function:
    Runtime: nodejs8.10
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: SecretTokenAuthorizer
        Authorizers:
          SecretTokenAuthorizer:
            FunctionArn: !GetAtt Authorizer.Arn
            # NOTE: Additional options:
            # FunctionInvokeRole: !Ref MyRole
            # Identity:
              # Header: Auth
              # ValidationExpression: Bearer.*
              # ReauthorizeEvery: 30 # seconds

  AuthorizerFunction:

  RequestHandlerFunction:
