Environment:
   Region: us-west-2
   Environment: test
   StackName: aws-multiregion-api-${Environment}-${Region}
   DeploymentBucket: deployment.${Region}
   DeploymentPrefix: ${StackName}
   Profile: default
CloudFormation:
   EnvironmentName: ${Environment}-${Region}
   AuthorizationTtlInSeconds: 30
   AuthorizerFunctionMemorySizeInMb: 128
   AuthorizerFunctionTimeoutInSeconds: 30
   RequestHandlerMemorySizeInMb: 128
   RequestHandlerTimeoutInSeconds: 30
   UserActivityTableWCU: 5
   UserActivityTableRCU: 5
   LogRetentionInDays: 14
Tags:
   Email: jim.gisler@gmail.com
   Application: ${StackName}
   EnvironmentName: ${Environment}-${Region}
